//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST.ImageServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ImageServiceReference1.ImageServiceSoap")]
    public interface ImageServiceSoap {
        
        // CODEGEN: Generating message contract since element name imageBytes from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadImage", ReplyAction="*")]
        TEST.ImageServiceReference1.UploadImageResponse UploadImage(TEST.ImageServiceReference1.UploadImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadImage", ReplyAction="*")]
        System.Threading.Tasks.Task<TEST.ImageServiceReference1.UploadImageResponse> UploadImageAsync(TEST.ImageServiceReference1.UploadImageRequest request);
        
        // CODEGEN: Generating message contract since element name fileName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetImage", ReplyAction="*")]
        TEST.ImageServiceReference1.GetImageResponse GetImage(TEST.ImageServiceReference1.GetImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetImage", ReplyAction="*")]
        System.Threading.Tasks.Task<TEST.ImageServiceReference1.GetImageResponse> GetImageAsync(TEST.ImageServiceReference1.GetImageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadImage", Namespace="http://tempuri.org/", Order=0)]
        public TEST.ImageServiceReference1.UploadImageRequestBody Body;
        
        public UploadImageRequest() {
        }
        
        public UploadImageRequest(TEST.ImageServiceReference1.UploadImageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadImageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string imageBytes;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileName;
        
        public UploadImageRequestBody() {
        }
        
        public UploadImageRequestBody(string imageBytes, string fileName) {
            this.imageBytes = imageBytes;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadImageResponse", Namespace="http://tempuri.org/", Order=0)]
        public TEST.ImageServiceReference1.UploadImageResponseBody Body;
        
        public UploadImageResponse() {
        }
        
        public UploadImageResponse(TEST.ImageServiceReference1.UploadImageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadImageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadImageResult;
        
        public UploadImageResponseBody() {
        }
        
        public UploadImageResponseBody(string UploadImageResult) {
            this.UploadImageResult = UploadImageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetImage", Namespace="http://tempuri.org/", Order=0)]
        public TEST.ImageServiceReference1.GetImageRequestBody Body;
        
        public GetImageRequest() {
        }
        
        public GetImageRequest(TEST.ImageServiceReference1.GetImageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetImageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileName;
        
        public GetImageRequestBody() {
        }
        
        public GetImageRequestBody(string fileName) {
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetImageResponse", Namespace="http://tempuri.org/", Order=0)]
        public TEST.ImageServiceReference1.GetImageResponseBody Body;
        
        public GetImageResponse() {
        }
        
        public GetImageResponse(TEST.ImageServiceReference1.GetImageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetImageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetImageResult;
        
        public GetImageResponseBody() {
        }
        
        public GetImageResponseBody(string GetImageResult) {
            this.GetImageResult = GetImageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImageServiceSoapChannel : TEST.ImageServiceReference1.ImageServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImageServiceSoapClient : System.ServiceModel.ClientBase<TEST.ImageServiceReference1.ImageServiceSoap>, TEST.ImageServiceReference1.ImageServiceSoap {
        
        public ImageServiceSoapClient() {
        }
        
        public ImageServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImageServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TEST.ImageServiceReference1.UploadImageResponse TEST.ImageServiceReference1.ImageServiceSoap.UploadImage(TEST.ImageServiceReference1.UploadImageRequest request) {
            return base.Channel.UploadImage(request);
        }
        
        public string UploadImage(string imageBytes, string fileName) {
            TEST.ImageServiceReference1.UploadImageRequest inValue = new TEST.ImageServiceReference1.UploadImageRequest();
            inValue.Body = new TEST.ImageServiceReference1.UploadImageRequestBody();
            inValue.Body.imageBytes = imageBytes;
            inValue.Body.fileName = fileName;
            TEST.ImageServiceReference1.UploadImageResponse retVal = ((TEST.ImageServiceReference1.ImageServiceSoap)(this)).UploadImage(inValue);
            return retVal.Body.UploadImageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TEST.ImageServiceReference1.UploadImageResponse> TEST.ImageServiceReference1.ImageServiceSoap.UploadImageAsync(TEST.ImageServiceReference1.UploadImageRequest request) {
            return base.Channel.UploadImageAsync(request);
        }
        
        public System.Threading.Tasks.Task<TEST.ImageServiceReference1.UploadImageResponse> UploadImageAsync(string imageBytes, string fileName) {
            TEST.ImageServiceReference1.UploadImageRequest inValue = new TEST.ImageServiceReference1.UploadImageRequest();
            inValue.Body = new TEST.ImageServiceReference1.UploadImageRequestBody();
            inValue.Body.imageBytes = imageBytes;
            inValue.Body.fileName = fileName;
            return ((TEST.ImageServiceReference1.ImageServiceSoap)(this)).UploadImageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TEST.ImageServiceReference1.GetImageResponse TEST.ImageServiceReference1.ImageServiceSoap.GetImage(TEST.ImageServiceReference1.GetImageRequest request) {
            return base.Channel.GetImage(request);
        }
        
        public string GetImage(string fileName) {
            TEST.ImageServiceReference1.GetImageRequest inValue = new TEST.ImageServiceReference1.GetImageRequest();
            inValue.Body = new TEST.ImageServiceReference1.GetImageRequestBody();
            inValue.Body.fileName = fileName;
            TEST.ImageServiceReference1.GetImageResponse retVal = ((TEST.ImageServiceReference1.ImageServiceSoap)(this)).GetImage(inValue);
            return retVal.Body.GetImageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TEST.ImageServiceReference1.GetImageResponse> TEST.ImageServiceReference1.ImageServiceSoap.GetImageAsync(TEST.ImageServiceReference1.GetImageRequest request) {
            return base.Channel.GetImageAsync(request);
        }
        
        public System.Threading.Tasks.Task<TEST.ImageServiceReference1.GetImageResponse> GetImageAsync(string fileName) {
            TEST.ImageServiceReference1.GetImageRequest inValue = new TEST.ImageServiceReference1.GetImageRequest();
            inValue.Body = new TEST.ImageServiceReference1.GetImageRequestBody();
            inValue.Body.fileName = fileName;
            return ((TEST.ImageServiceReference1.ImageServiceSoap)(this)).GetImageAsync(inValue);
        }
    }
}
