//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ImageServiceSoap")]
    public interface ImageServiceSoap {
        
        // CODEGEN: Generating message contract since element name imageBytes from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadImage", ReplyAction="*")]
        TEST.ServiceReference1.UploadImageResponse UploadImage(TEST.ServiceReference1.UploadImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadImage", ReplyAction="*")]
        System.Threading.Tasks.Task<TEST.ServiceReference1.UploadImageResponse> UploadImageAsync(TEST.ServiceReference1.UploadImageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadImage", Namespace="http://tempuri.org/", Order=0)]
        public TEST.ServiceReference1.UploadImageRequestBody Body;
        
        public UploadImageRequest() {
        }
        
        public UploadImageRequest(TEST.ServiceReference1.UploadImageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadImageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string imageBytes;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileName;
        
        public UploadImageRequestBody() {
        }
        
        public UploadImageRequestBody(string imageBytes, string fileName) {
            this.imageBytes = imageBytes;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadImageResponse", Namespace="http://tempuri.org/", Order=0)]
        public TEST.ServiceReference1.UploadImageResponseBody Body;
        
        public UploadImageResponse() {
        }
        
        public UploadImageResponse(TEST.ServiceReference1.UploadImageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadImageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadImageResult;
        
        public UploadImageResponseBody() {
        }
        
        public UploadImageResponseBody(string UploadImageResult) {
            this.UploadImageResult = UploadImageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImageServiceSoapChannel : TEST.ServiceReference1.ImageServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImageServiceSoapClient : System.ServiceModel.ClientBase<TEST.ServiceReference1.ImageServiceSoap>, TEST.ServiceReference1.ImageServiceSoap {
        
        public ImageServiceSoapClient() {
        }
        
        public ImageServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImageServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TEST.ServiceReference1.UploadImageResponse TEST.ServiceReference1.ImageServiceSoap.UploadImage(TEST.ServiceReference1.UploadImageRequest request) {
            return base.Channel.UploadImage(request);
        }
        
        public string UploadImage(string imageBytes, string fileName) {
            TEST.ServiceReference1.UploadImageRequest inValue = new TEST.ServiceReference1.UploadImageRequest();
            inValue.Body = new TEST.ServiceReference1.UploadImageRequestBody();
            inValue.Body.imageBytes = imageBytes;
            inValue.Body.fileName = fileName;
            TEST.ServiceReference1.UploadImageResponse retVal = ((TEST.ServiceReference1.ImageServiceSoap)(this)).UploadImage(inValue);
            return retVal.Body.UploadImageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TEST.ServiceReference1.UploadImageResponse> TEST.ServiceReference1.ImageServiceSoap.UploadImageAsync(TEST.ServiceReference1.UploadImageRequest request) {
            return base.Channel.UploadImageAsync(request);
        }
        
        public System.Threading.Tasks.Task<TEST.ServiceReference1.UploadImageResponse> UploadImageAsync(string imageBytes, string fileName) {
            TEST.ServiceReference1.UploadImageRequest inValue = new TEST.ServiceReference1.UploadImageRequest();
            inValue.Body = new TEST.ServiceReference1.UploadImageRequestBody();
            inValue.Body.imageBytes = imageBytes;
            inValue.Body.fileName = fileName;
            return ((TEST.ServiceReference1.ImageServiceSoap)(this)).UploadImageAsync(inValue);
        }
    }
}
